CREATE SEQUENCE CUSTOMER_SEQ
    START WITH 10000
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE CUSTOMER
(
    ID                           BIGINT NOT NULL,
    USERNAME                     VARCHAR NOT NULL UNIQUE,
    FIRST_NAME                   VARCHAR NOT NULL,
    LAST_NAME                    VARCHAR NOT NULL,
    EMAIL                        VARCHAR NOT NULL,
    ADDRESS_STREET               VARCHAR NOT NULL,
    ADDRESS_CITY                 VARCHAR NOT NULL,
    ADDRESS_STATE_PROVINCE       VARCHAR,
    ADDRESS_POSTAL_CODE          VARCHAR NOT NULL,
    ADDRESS_COUNTRY              VARCHAR NOT NULL,
    CREDIT_CARD_TYPE             VARCHAR NOT NULL,
    CREDIT_CARD_NUMBER           VARCHAR NOT NULL,
    CREDIT_CARD_EXPIRATION_MONTH INTEGER NOT NULL,
    CREDIT_CARD_EXPIRATION_YEAR  INTEGER NOT NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE PAYMENT_SEQ
    START WITH 1000
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE PAYMENT
(
    ID                 BIGINT       NOT NULL,
    PAYMENT_DATE       TIMESTAMP     NOT NULL,
    AMOUNT             NUMERIC(7, 2) NOT NULL,
    CREDIT_CARD_NUMBER VARCHAR       NOT NULL,
    TRANSACTION_ID     VARCHAR       NOT NULL,
    PRIMARY KEY (ID)
);

CREATE SEQUENCE BOOK_ORDER_SEQ
    START WITH 100000
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE BOOK_ORDER
(
    ID                     BIGINT       NOT NULL,
    ORDER_DATE             TIMESTAMP     NOT NULL,
    AMOUNT                 NUMERIC(7, 2) NOT NULL,
    STATUS                 VARCHAR       NOT NULL,
    CUSTOMER_ID            BIGINT        NOT NULL REFERENCES CUSTOMER (ID),
    ADDRESS_CITY           VARCHAR       NOT NULL,
    ADDRESS_COUNTRY        VARCHAR       NOT NULL,
    ADDRESS_POSTAL_CODE    VARCHAR       NOT NULL,
    ADDRESS_STATE_PROVINCE VARCHAR,
    ADDRESS_STREET         VARCHAR       NOT NULL,
    PAYMENT_ID             BIGINT        NOT NULL REFERENCES PAYMENT (ID),
    PRIMARY KEY (ID)
);

CREATE SEQUENCE ORDER_ITEM_SEQ
    START WITH 1000
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE ORDER_ITEM
(
    ID             BIGINT       NOT NULL,
    BOOK_ISBN      VARCHAR       NOT NULL,
    BOOK_TITLE     VARCHAR       NOT NULL,
    BOOK_AUTHORS   VARCHAR       NOT NULL,
    BOOK_PUBLISHER VARCHAR       NOT NULL,
    BOOK_PRICE     NUMERIC(5, 2) NOT NULL,
    QUANTITY       INTEGER       NOT NULL,
    ORDER_ID       BIGINT        NOT NULL REFERENCES BOOK_ORDER (ID),
    PRIMARY KEY (ID)
);
